{% set name = "gwtc-tools" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gwtc_tools-{{ version }}.tar.gz
  sha256: f64c749c49de1f69de6ee987b6c53625784af7f4ffa4c596a62e5ccefa18a202

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - gwtc_update_pipeline_gevents = gwtc:gwtc_update_pipeline_gevents
    - gwtc_diff = gwtc:gwtc_diff
    - gwtc_get_gevent_coinc_files = gwtc:gwtc_get_gevent_coinc_files
    - gwtc_create_from_query = gwtc:gwtc_create_from_query
    - gwtc_revert = gwtc:gwtc_revert

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=42
    - setuptools-scm >=3.4.3
    - wheel
  run:
    - python >=3.6
    - ligo-gracedb
    - pyyaml

test:
  imports:
    - gwtc
  commands:
    - pip check
    - gwtc_update_pipeline_gevents --help
    - gwtc_diff --help
    - gwtc_get_gevent_coinc_files --help
    - gwtc_create_from_query --help
    - gwtc_revert --help
  requires:
    - pip

about:
  home: https://git.ligo.org/chad-hanna/gwtc
  summary: A package for gwtc operations, including interactions with gracedb
  description: |
    A library for creating and interacting with Gravitational Wave Transient
    Catalogs in gracedb. This package provides tools for managing gravitational
    wave transient catalogs and integrating with GraceDB.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://git.ligo.org/chad-hanna/gwtc
  doc_url: https://git.ligo.org/chad-hanna/gwtc

extra:
  recipe-maintainers:
    - chadhanna
